---
- hosts: 9.190.27.146
  user: anstadm
  become: true
  gather_facts: False
  tasks:
    - name: create logical volume testlv
      command: mklv -t jfs2 -y testlv db2vg 16
      args:
        creates: /dev/testlv
    - name: create file system /test1
      command: crfs -v jfs2 -A yes -m /test1 -d /dev/testlv
      args:
        creates: /test1
    - name: mount /test1
      mount: name=/test1 src="/dev/testlv" state=mounted fstype=jfs2
